### ISSUE TITLE
flysystem cache not working

### ISSUE THREAD

**Issue by theTigerDuck** [pstaender/silverstripe-redis-cache#12]
Class League\Flysystem\Cached\Storage\Predis does not exist in an actual silverstripe. Why dont use https://github.com/jgivoni/flysystem-cache-adapter? And how do I use it?
Tryed to install league/flysystem-aws-s3-v3 ^1.0 but silverstripe/s3 is locked to version 3.0.1 so how to deal with it?

**Comment by elliot-sawyer** [comment]
Not sure how to help you resolve this, this module is not Flysystem, nor Predis, nor Silverstripe S3

**Comment by elliot-sawyer** [comment]
A quick Google search led me to this: https://github.com/thephpleague/flysystem-cached-adapter/blob/master/src/Storage/Predis.php

**Comment by theTigerDuck** [comment]
Well thats outdated and only works with flysystem v1 silverstripe use v3. It's mentioned readme so it should work don't you think?

```
---
Name: silverstripes3-flysystem-redis
Only:
  envvarset:
    - REDIS_URL
After:
  - '#silverstripes3-flysystem'
---
SilverStripe\Core\Injector\Injector:
  League\Flysystem\Cached\Storage\Memory.public:
    class: League\Flysystem\Cached\Storage\Predis
  League\Flysystem\Cached\Storage\Adapter.public:
    class: League\Flysystem\Cached\Storage\Predis
  League\Flysystem\Cached\Storage\Adapter.protected:
    class: League\Flysystem\Cached\Storage\Predis`
```

**Comment by elliot-sawyer** [comment]
Not at all, This module does not depend on Silverstripe S3 or require it in any way. That suggested configuration is a sample, and there if you happen to be using Flysystem. Perhaps you could raise a pull request to make the documentation more clear, if you believe it's outdated? 

Let's put this another way - what change are you expecting the maintainers to make to this module to enable you to use Flysystem in the manner suggested? Again, this module does not require Flysystem or S3.
