### ISSUE TITLE
Strange error on /dev/build

### ISSUE THREAD

**Issue by lars-lemon8** [pstaender/silverstripe-redis-cache#13]
Hi,

After enabling the redis cachefactory for SilverStripe\Core\Cache\CacheFactory , my sites (SS5.2 / SS5.3) won't build anymore.

ERROR [Emergency]: Uncaught Exception: Missing graphql file for Query

IN GET /dev/build

Line 125 in /xxxxxx/site/vendor/silverstripe/graphql/src/Schema/Storage/AbstractTypeRegistry.php

Looking into the piece of code, it seems to expect something to be there on the filesystem,  regardless of cache settings (see below). 

Can anyone else confirm this is happening for them too ?  If not, I will try and setup a clean reproducable environment.

` protected static function fromCache(string $typename)
117     {
118         /* @var NameObfuscator $obfuscator */
119         $obfuscator = Injector::inst()->get(NameObfuscator::class);
120         $type = null;
121         if (!isset(static::$types[$typename])) {
122             $obfuscatedName = $obfuscator->obfuscate($typename);
123             $file = static::getSourceDirectory() . DIRECTORY_SEPARATOR . $obfuscatedName . '.php';
124             if (!file_exists($file)) {
125                 throw new Exception('Missing graphql file for ' . $typename);
126             }
127             require_once($file);
128             $cls = static::getSourceNamespace() . '\\' . $obfuscatedName;
129             if (!class_exists($cls)) {
130                 throw new Exception('Missing graphql class for ' . $typename);
131             }`

**Comment by elliot-sawyer** [comment]
Can you post your config? I haven't seen this before on SS 5.2

`composer info silverstripe/graphql` might help as well

**Comment by lars-lemon8** [comment]
Hi Elliot,

Thanks for your reply.  I'm having a haaaaaard time reproducing this in a dependable way (for example, I can't reproduce it locally,  and not on all of our dev servers.  I'm getting suspicious about the differences in environments.   I'll f**k around more and re-open the ticket when (or if) I find something actionable.    ;-)

**Comment by elliot-sawyer** [comment]
All good, I'd normally suggest that there's nothing in this module related to graphql so not sure what we can fix here, but I'm only mentioning this because this is a common thing that I replace in my own site configs.
