### ISSUE TITLE
Stable release tag?

### ISSUE THREAD

**Issue by phptek** [pstaender/silverstripe-redis-cache#4]
Is there any chance you can issue a stable release tag to save lib consumers having to encode `dev-master` into `composer.json`? Cheers!

**Comment by pstaender** [comment]
Hi @phptek , I've created a new [version tag](https://github.com/pstaender/silverstripe-redis-cache/releases/tag/0.0.2).

I would consider `master`/`main` always as production ready / stable. For larger changes there would be an extra branch before merging into the stable branch.
